service: serverless-ipsum-js # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  ipsum:
    handler: handler.ipsum
    events:
      - http:
          method: get
          path: /
